services:
    form.type.bigfoot_contextualizable_entities:
        class: Bigfoot\Bundle\ContextBundle\Form\ContextualizableEntitiesType
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: bigfoot_contextualizable_entities }
    bigfoot_context:
        class:        "Bigfoot\\Bundle\\ContextBundle\\Model\\Context"
        arguments:    [ @service_container ]
    bigfoot_language_loader:
        class:        "Bigfoot\\Bundle\\ContextBundle\\ContextLoader\\LanguageLoader"
        arguments:    [ @service_container ]
    bigfoot.listener.bigfoot_core_kernel_listener:
        class: Bigfoot\Bundle\ContextBundle\Listener\KernelListener
        arguments: [ @bigfoot_context ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10 }

    # Menu Listener
    bigfoot_context.listener.menu:
        class: Bigfoot\Bundle\ContextBundle\Listener\MenuListener
        tags:
            - { name: kernel.event_subscriber }